import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
let token = sessionStorage.getItem('worker-management') || '';
async function api(path: string, method = 'GET', body?: any) {
  const response = await fetch('/management/api/' + path, { method, headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json(); if (!response.ok) throw Error(data.detail || '请求失败'); return data;
}
const statusNames:Record<string,string>={disabled:'已停用',checking:'检查中',checked:'检查通过',ready:'可接单',error:'故障',draining:'等待停用',running:'执行中',succeeded:'完成',failed:'失败'};
function App() {
  const [connected,setConnected] = useState(false), [credential,setCredential] = useState(token), [data,setData] = useState<any>(null), [page,setPage] = useState('overview');
  const [error,setError] = useState(''), [operations,setOperations] = useState<any[]>([]), [config,setConfig] = useState(''), [kind,setKind] = useState('image'), [access,setAccess] = useState<any>(null), [report,setReport] = useState<any>(null);
  const refresh = async () => { const [d,o] = await Promise.all([api('overview'),api('operations')]);setData(d);setOperations(o);setConnected(true); };
  useEffect(() => { if (!token) return; void refresh().catch(e=>setError(e.message)); const t=setInterval(()=>void refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(t); },[connected]);
  async function act(path:string,body:any={},method='POST') { try { setError('');await api(path,method,body);await refresh();if(path==='access')setAccess(await api('access')); }catch(e){setError((e as Error).message);} }
  const [installDir,setInstallDir]=useState(''), [python,setPython]=useState(''), [installPlan,setInstallPlan]=useState<any>(null);
  const names:Record<string,string>={overview:'概览',executors:'执行器',environment:'环境',access:'接入',diagnostics:'诊断'};
  return <><header><b>◈ Zhilume <small>WORKER</small></b><span>当前机器管理</span></header>{!connected?<main><h1>连接 Worker 管理台</h1><p>使用部署管理凭证。Server 的任务接入凭证不能修改本机环境。</p><form onSubmit={e=>{e.preventDefault();token=credential;sessionStorage.setItem('worker-management',token);void refresh().catch(e=>setError(e.message));}}><input type="password" aria-label="部署管理凭证" value={credential} onChange={e=>setCredential(e.target.value)}/><button>连接</button></form><p>在部署机器执行：<code>zhilume-worker --state /path/to/state --show-management-token</code></p></main>:<div className="layout"><nav>{Object.entries(names).map(([k,v])=><button className={page===k?'active':''} key={k} onClick={()=>{setPage(k);if(k==='access')void api('access').then(setAccess,e=>setError(e.message));}}>{v}</button>)}</nav><main><h1>{names[page]}</h1>
    {page==='overview'&&data&&<><div className="cards"><article><strong>服务在线</strong><p>v{data.version} · {data.name}</p></article><article><strong>{data.serverConnected?'Server 已连接':data.bound?'已绑定 · 未连接':'未绑定'}</strong><p>独立配置与诊断始终可用</p></article><article><strong>{(data.disk.free/1024**3).toFixed(1)} GB</strong><p>磁盘可用空间</p></article></div><h2>GPU 与资源</h2>{data.gpus.length?data.gpus.map((g:any)=><article key={g.uuid}>{g.name}<p>{g.uuid}</p><p>显存 {g.usedMiB} / {g.totalMiB} MiB</p></article>):<p>未发现 NVIDIA GPU，管理服务可正常使用。</p>}{data.resourceQuarantined&&<p role="alert">GPU 资源释放未确认，已隔离；请检查推理服务后重新启用。</p>}<h2>当前任务</h2><pre>{data.tasks.length ? data.tasks.map((t:any)=>`${t.jobId} · ${t.cancelling?'取消中':'执行中'}`).join('\n') : '当前没有任务'}</pre></>}
    {page==='executors'&&data?.executors.map((x:any)=><article key={x.id}><h2>{{image:'Qwen / ComfyUI',speech:'IndexTTS',video:'H3'}[x.id as 'image']}</h2><p>状态：{statusNames[x.state]||x.state} · 真实推理：{x.inferenceVerified?'已通过':'尚未验证'}</p>{x.reason&&<p role={x.state==='error'?'alert':'status'}>{x.reason}</p>}<div className="actions"><button onClick={()=>void act(`executors/${x.id}/check`)}>检查环境与模型</button><button onClick={()=>void act(`executors/${x.id}/enable`)}>启用</button><button onClick={()=>void act(`executors/${x.id}/disable`,{policy:'wait'})}>完成任务后停用</button><button onClick={()=>void act(`executors/${x.id}/disable`,{policy:'cancel'})}>取消任务并停用</button></div><small>启用不会执行测试推理。停用必须确认进程停止和资源释放。</small></article>)}
    {page==='environment'&&<article><p>复用已有环境；程序、模型、Python 与工作目录由配置指定。保存不会安装依赖、下载模型或运行 GPU。</p><label>执行器<select value={kind} onChange={e=>{setKind(e.target.value);setConfig(JSON.stringify(data.executors.find((x:any)=>x.id===e.target.value)?.config||{},null,2));}}>{['image','speech','video'].map(k=><option key={k}>{k}</option>)}</select></label><button onClick={()=>setConfig(JSON.stringify(data.executors.find((x:any)=>x.id===kind)?.config||{},null,2))}>读取当前配置</button><label>部署配置 JSON<textarea rows={20} value={config} onChange={e=>setConfig(e.target.value)}/></label><button onClick={()=>{try{void act(`executors/${kind}/config`,JSON.parse(config),'PUT');}catch{setError('JSON 格式无效');}}}>保存配置并停用</button><details><summary>安装独立标准环境（Linux / WSL2）</summary><p>只下载程序与依赖；不下载模型、不启动 GPU。安装使用新目录，现有环境保持独立。</p><label>新安装目录<input value={installDir} onChange={e=>{setInstallDir(e.target.value);setInstallPlan(null);}}/></label><label>已有 Python 绝对路径<input value={python} onChange={e=>{setPython(e.target.value);setInstallPlan(null);}}/></label><button onClick={()=>void api('install','POST',{kind,directory:installDir,python}).then(setInstallPlan,e=>setError(e.message))}>查看安装计划</button>{installPlan&&<><pre>{JSON.stringify(installPlan,null,2)}</pre><button onClick={()=>void act('install',{kind:installPlan.kind,directory:installPlan.directory,python,execute:true})}>执行依赖安装</button></>}</details></article>}
    {page==='access'&&access&&<article><label>名称<input value={access.name} onChange={e=>setAccess({...access,name:e.target.value})}/></label><label>监听地址<input value={access.host} onChange={e=>setAccess({...access,host:e.target.value})}/></label><label>端口<input type="number" value={access.port} onChange={e=>setAccess({...access,port:+e.target.value})}/></label><button onClick={()=>void act('access',{action:'configure',name:access.name,host:access.host,port:access.port})}>保存（监听变更需重启服务）</button><p>任务接入凭证</p><input type="password" readOnly value={access.credential}/><button onClick={()=>void navigator.clipboard.writeText(access.credential)}>复制接入凭证</button><p>绑定 Server：{access.boundServerId||'无'}</p><button onClick={()=>void act('access',{action:'unbind'})}>解除绑定</button><button onClick={()=>void act('access',{action:'rotate'})}>更换接入凭证并解除绑定</button></article>}
    {page==='diagnostics'&&<article><button onClick={()=>void api('diagnostics').then(setReport,e=>setError(e.message))}>生成脱敏诊断报告</button>{report&&<><pre>{JSON.stringify(report,null,2)}</pre><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='worker-diagnostics.json';a.click();URL.revokeObjectURL(url);}}>下载报告</button></>}</article>}
    {operations.length>0&&<article><h2>部署操作</h2>{operations.slice(-5).map(o=><p key={o.id}>{o.name} · {o.state}{o.error?' · '+o.error:''}</p>)}</article>}
  </main></div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}</>;
}
createRoot(document.getElementById('root')!).render(<App/>);
